package com.green.greenstock.repository.model;

import java.time.LocalDate;

import com.fasterxml.jackson.databind.PropertyNamingStrategies;
import com.fasterxml.jackson.databind.annotation.JsonNaming;

import lombok.Data;
/*
 * https://github.com/koreainvestment/open-trading-api/blob/main/stocks_info/%EC%A2%85%EB%AA%A9%EB%A7%88%EC%8A%A4%ED%84%B0%EC%A0%95%EB%B3%B4(%EC%BD%94%EC%8A%A4%ED%94%BC).h
 */
@Data
@JsonNaming(PropertyNamingStrategies.SnakeCaseStrategy.class)
public class KospiCode {
	
	private String mkscShrnIscd; // 단축코드
	private String stndIscd; // 표준코드
	private String htsKorIsnm; // 한글종목명
	private String scrtGrpClsCode; // 증권그룹구분코드
	private double avlsScalClsCode; // 시가총액 규모 구분 코드 유가 (0:제외 1:대 2:중 3:소)
	private int bstpLargDivCode; // 지수 업종 대분류 코드
	private int bstpMedmDivCode; // 지수 업종 중분류 코드
	private int bstpSmalDivCode; // 지수 업종 소분류 코드
	private String mninClsCodeYn; // 제조업 구분 코드 (Y/N)
	private String lowCurrentYn; // 저유동성종목 여부
	private String sprnStrrNmixIssuYn; // 지배 구조 지수 종목 여부 (Y/N)
	private String kospi200ApntClsCode; // KOSPI200 섹터업종 (0:미분류 1:건설기계 2:조선운송 3:철강소재 4:에너지화학 5:정보통신 6:금융 7:필수소비재 8: 자유소비재)
	private String kospi100IssuYn; // KOSPI100여부
	private String kospi50IssuYn; // KOSPI50여부
	private String krxIssuYn; // KRX 종목 여부
	private String etpProdClsCode; // ETP 상품구분코드 (0:해당없음 1:투자회사형 2:수익증권형 3:ETN 4:손실제한ETN)
	private String elwPblcYn; // ELW 발행여부 (Y/N)
	private String krx100IssuYn; // KRX100 종목 여부 (Y/N)
	private String krxCarYn; // KRX 자동차 여부
	private String krxSmcnYn; // KRX 반도체 여부
	private String krxBioYn; // KRX 바이오 여부
	private String krxBankYn; // etc...
	private String etprUndtObjtCoYn; // etc...
	private String krxEnrgChmsYn; // etc...
	private String krxStelYn; // etc...
	private int shortOverClsCode; // etc...
	private String krxMediCmncYn; // etc...
	private String krxCnstYn; // etc...
	private String krxFnncSvcYn; // etc...
	private String krxScrtYn; // etc...
	private String krxShipYn; // etc...
	private String krxInsuYn; // etc...
	private String krxTrnpYn; // etc...
	private String sriNmixYn; // etc...
	private int stckSdpr; // etc...
	private int frmlMrktDealQtyUnit; // etc...
	private int ovtmMrktDealQtyUnit; // etc...
	private String trhtYn; // etc...
	private String sltrYn; // etc...
	private String mangIssuYn; // etc...
	private int mrktAlrmClsCode; // etc...
	private String mrktAlrmRiskAdntYn; // etc...
	private String insnPbntYn; // etc...
	private String bypsLstnYn; // etc...
	private int flngClsCode; // etc...
	private int fcamModClsCode; // etc...
	private int icicClsCode; // etc...
	private int margRate; // etc...
	private String crdtAble; // etc...
	private int crdtDays; // etc...
	private int prdyVol; // etc...
	private int stckFcam; // etc...
	private LocalDate stckLstnDate; // etc...
	private int lstnStcn; // etc...
	private int cpfn; // etc...
	private int stacMonth; // etc...
	private String poPrc; // etc...
	private int prstClsCode; // etc...
	private String sstsHotYn; // etc...
	private String stangeRunupYn; // etc...
	private String krx300IssuYn; // etc...
	private String kospiIssuYn; // etc...
	private int saleAccount; // etc...
	private int bsopPrfi; // etc...
	private int opPrfi; // etc...
	private int thtrNtin; // etc...
	private String roe; // etc...
	private LocalDate baseDate; // etc...
	private int prdyAvlsScal; // etc...
	private String grpCode; // etc...
	private String coCrdtLimtOverYn; // etc...
	private String secuLendAbleYn; // etc...
	private String stlnAbleYn; // etc...


}
